# ----- Laser -----
tilt_laser:
  cb_detector_config:  /tilt_laser/cb_detector_config
  settler_config:      /tilt_laser/settler_config

  configs:
    cb_8x6:
      settler:
        tolerance: 2.00
        ignore_failures: False
        max_step: 45.0
        cache_size: 10
      cb_detector:
        active: True
        num_x: 8
        num_y: 6
        spacing_x: 0.0249
        spacing_y: 0.0249
        width_scaling: 2
        height_scaling: 2
        subpixel_window: 6
        subpixel_zero_zone: 2
        flip_horizontal: 1
        min_intensity: 1500
        max_intensity: 3000
